[build]
  publish = "public"
  functions = "netlify/functions"
  command = "pip install -r netlify/functions/remove-bg/requirements.txt -t netlify/functions/remove-bg/"

[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
