[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  publish = "public"
  functions = "netlify/functions"
  port = 8888

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["encoding"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
