[build]
  publish = "public"
  functions = "netlify/functions"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[[plugins]]
  package = "@netlify/plugin-python"
  [plugins.inputs]
    requirements = "netlify/functions/remove-bg/requirements.txt"

[functions]
  external_node_modules = ["sharp"]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
